### ISSUE TITLE
Wordpress permalinks confusion

### ISSUE THREAD

**Issue by dridi** [varnish/varnish-wiki#3]
See this thread on the varnish-misc mailing list:

https://www.varnish-cache.org/lists/pipermail/varnish-misc/2017-March/025685.html

Cheers

**Comment by freshteapot** [comment]
I have read the link above and it would be a lot easier if you went into detail in the description of this issue what you are after. As I am not sure what this issue is meant to address.

**Comment by dvershinin** [comment]
See pull request #4 about what he meant :)

**Comment by magicalwonders** [comment]
Here's the extract of what I wrote on the varnish-misc list -

Step 3 says to enable custom permalinks in Wordpress typing /%year%/%monthnum%/%post_id%  - My existing Wordpress sites all have custom Permalinks. However they are mostly in the format of  /%postname%/  I don't really want to have to change all the permalinks. Will Varnish still work ok for sites with custom Permalinks set at /%postname%/ ?
---------------------------------------------------------------------------------------------

Maybe advising that any custom Permalinks links should be enabled rather than specifying a particular structure would be less confusing?

**Comment by huayra** [comment]
I think your proposal is good and understandable. Merged!
